# Generated by Django 5.0.3 on 2024-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="separate_fats",
            field=models.BooleanField(default=True),
        ),
    ]
