# Generated by Django 5.0.3 on 2024-03-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("time_of_serving", models.DateTimeField(auto_now_add=True)),
                (
                    "serving_type",
                    models.CharField(
                        choices=[("fiber", "Fiber"), ("fat", "Fat")], max_length=30
                    ),
                ),
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                ("fiber_actual", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fat_actual", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField()),
                ("progress_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
