# Generated by Django 5.0.3 on 2024-03-29 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="current_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="log",
            name="time_of_serving",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
