# # build and run beat container
# docker build -t beanlife-beat -f Dockerfile.celerybeat .
# docker run -d beanlife-beat

# # build and run worker container
# docker build -t beanlife-worker -f Dockerfile.celeryworker .
# docker run -d beanlife-worker
