#using same base image as main Dockerfile
FROM python:3.10-bullseye
ENV PYTHONUNBUFFERED 1

RUN python -m pip install --upgrade pip
RUN python -m pip install python-dotenv

WORKDIR /app
COPY . /app/
RUN pip install --no-cache-dir -r requirements.txt

# Set the command to start the Celery worker
CMD celery -A beanlife worker -l info -B beat

# CMD celery -A beanlife beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
# CMD celery -A beanlife worker -l info
