version: '3'

volumes:
  bean-db:
    external: true

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - bean-db:/data

    environment:
      - SQLITE_DB_PATH=/data/db.sqlite3
    depends_on:
      - redis
    networks:
      - redis-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celeryworker
    image: beanlife_celery_worker
    command: celery -A beanlife worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - redis-network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celerybeat
    image: beanlife_celery_beat
    command: celery -A beanlife beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - redis-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
